### ISSUE TITLE
When used in a workspace, behavior is different from other cargo subcommands

### ISSUE THREAD

**Issue by dralley** [flamegraph-rs/flamegraph#180]
If you're inside a sub-dir of a workspace, most cargo commands such as "cargo test", "cargo build", "cargo check", "cargo bench" will only operate on any crates in or beneath the current directory. e.g. If you have a workspace with multiple crates and you `cd` into one of those crate directories, cargo will only build that crate, test that crate, bench that crate, etc. - unless you tell it otherwise with the "--workspace" flag.

But "cargo flamegraph" will attempt to compile the whole workspace.  It appears you can select an individual crate with "--package" but it would be better and more consistent UX for it to behave the same as other cargo commands.

**Comment by djc** [comment]
@ede1998 would you be up for fixing this?

**Comment by ede1998** [comment]
Sure, I can look into it.

**Comment by ede1998** [comment]
Ok I analyzed the issue a bit.

I would not expect `cargo flamegraph` to compile the whole workspace. It just calls `cargo build` so it should behave the same in regards to compiling.

@dralley Are you explicitly referring to compilation that is done for the whole workspace? Because I'm not sure that I can reproduce the issue in that case. Or are you just trying to say that `cargo flamegraph`s target selection works different to `cargo run` etc.? I.e. `cargo flamegraph` in a package of a workspace would try to run any binary target in the workspace while `cargo run` runs the binary in the current package.

What I found is that the (automatic) target selection acts a bit different to what one might expect based on `cargo build`s behaviour.
- `cargo flamegraph` chooses the target from the entire workspace, not just packages in the working directory and below.
- `cargo flamegraph` suggests the targets from the entire workspace, not just packages in the working directory and below (if it cannot decide for itself).

So we should probably restrict the target selection to just choose from the working directory and its children. I'll probably make a PR sometime this week.

**Comment by dralley** [comment]
In this specific case I was trying to flamegraph a library and using the --unit-tests flag so that it would execute my test code.  But it was compiling the whole workspace, and I had other crates in the workspace with compile errors.

**Comment by ede1998** [comment]
Did you try the `-v` flag to see the build command `cargo flamegraph` tries to execute? If you just run this command, does it fail? How about just `cargo test` to run the unit tests, does this work?

As I said, `cargo flamegraph` shouldn't compile the other crates in the workspace unless the target depends on them.
Now that I think of it, what version of `cargo flamegraph` are you using? I don't know how the older versions would handle a workspace.

**Comment by dralley** [comment]
I have the newest version, but I can't figure out what exact command I ran - and now, I'm having difficulty reproducing the problem.

**Comment by ede1998** [comment]
Ok, I changed `cargo flamegraph` to be more similar to the standard cargo commands when it comes to using workspaces (see #182).

However I couldn't reproduce your compile issue so if you manage to reproduce it again please tell me how and I can look again.

**Comment by dralley** [comment]
Separate issue which may already be addressed by the patch: if the test or bench tries to load a file from a path relative to the sub-crate, the test / bench will be able to execute normally but will fail under `cargo flamegraph`.

I'll test that under the patch when I get a chance.
