### ISSUE TITLE
Allow user to specify language for coloring flame graph

### ISSUE THREAD

**Issue by jonhoo** [flamegraph-rs/flamegraph#19]
Inferno supports setting a color palette for the flame graph (just like `flamegraph.pl --colors`), and some of the palettes (see [`MultiPalette`](https://docs.rs/inferno/0.5.0/inferno/flamegraph/color/enum.MultiPalette.html)) are specifically designed to highlight particular languages well. It'd be cool if `cargo flamegraph` let you pass a `--lang` parameter to select the language to color the flame graph as! Speaking of, it'd be _really_ neat if we also had support for a Rust coloring that, say, colors functions from `std` and `core` differently from user functions!

**Comment by zthompson47** [comment]
I found this issue because I was looking for a way to set higher contrast color palettes in the flamegraph for readability.  I hadn't thought of a `--lang` option, and that might even solve my original problem because the readability issue mostly comes from looking for a specific part of my user code in the flamegraph.

So, I implemented a basic version of this feature and I'd like to touch base and see if I should start a PR.  I added the following parameters:
```
-C, --colors <colors>  Color palette [possible values: hot, mem, io, red, green, blue, aqua, yellow, purple, orange]
-l, --lang <lang>      Color palette based on language semantics [possible values: java, perl, js]
```

I'd also like to work on the Rust specific coloring.  Would that happen over in the `inferno` repo?

**Comment by djc** [comment]
I'd be happy to review a PR for `--colors` and `--lang` options. I think a Rust color would indeed happen on the inferno side.

**Comment by zthompson47** [comment]
Thanks for the review offer!

I've implemented the Rust language coloring in the inferno repo, and I'm trying to figure out how to eventually get those changes working over here.  This repository will need to use the updated inferno repo after (assuming) my PR is merged.  Otherwise there will be an error in the cli with `--lang rust` (runtime, but not at compile, I believe).

I'm guessing it's best to wait and file another PR here if everything goes well with my first two.  I don't have a lot of git collaboration experience, so I'm looking for a bit of guidance on this one.  Thanks!

**Comment by djc** [comment]
I think the PR here will be fully independent of the inferno one, so it's fine to move ahead. It seems likely that we'll be able to pick up the Rust language option automatically as soon as an updated version of inferno is released.

**Comment by djc** [comment]
@jonhoo I noticed only Palette implements FromStr, and BasicPalette and MultiPalette don't. What do you think the CLI UX should look like?

**Comment by jonhoo** [comment]
It's a good question — flamegraph doesn't currently distinguish between "language" palettes and "color" palettes really, and so inferno doesn't either. I _think_ that's probably the right call to be honest, because it gets really weird to try to combine, say, the I/O coloring with the Rust coloring. My guess is that a simple `--palette` is the way to go, and then you could have `--lang` as a dedicated option that `conflicts_with("palette")`, has `valid_values(["java", "perl", "rust"])`, and behind the scenes just sets the palette. Alternatively, if you're thinking that `flamegraph.rs` is really mainly for Rust programs, just default to passing in `rust` as the palette and allow passing in `--palette`.

**Comment by djc** [comment]
Let's start with just having a single `--palette` that uses the `FromStr` impl on inferno's `Palette` to pick something (no default).

**Comment by zthompson47** [comment]
Thanks for the feedback - I'll get another commit prepared with the single `--palette` option.  That seems to keep things open-ended for now.

**Comment by zthompson47** [comment]
I pushed another commit with the `--palette` option, but it will generate a runtime error with `--palette rust` until the `inferno` repo is updated.  There might be a way around the error, but it requires adding `clap` as a dependency and using the `arg_enum!` macro to let `structopt` magically generate a list of options for a wrapper enum around `Palette`.

In any case, it might be good as-is, and we could address possible issues in the code review.
